/* Meaningful cultural reading, local authoring, export and offline continuity checks. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'..'),lab=path.join(root,'design-lab'),read=n=>fs.readFileSync(path.join(lab,n),'utf8'),results=[];
function make(name,query='',settings={}){
 const dom=new JSDOM(read(name),{url:'https://poc.example/'+name+query,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:new VirtualConsole()}),w=dom.window;
 w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{};
 if(settings.notes)w.localStorage.setItem('ehime-v2-field-observations',JSON.stringify(settings.notes));
 if(settings.blocked)Object.defineProperty(w,'localStorage',{get(){throw Error('blocked')}});
 for(const s of w.document.querySelectorAll('script:not([src])'))w.eval(s.textContent);
 for(const n of ['experience-data.js','experience.js','legacy-ui.js','culture-experience.js'])w.eval(read(n));return dom;
}
async function test(name,fn){try{await fn();results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',error:e.message})}}
async function main(){
await test('Homepage reaches culture before all six compact event entries',()=>{const d=make('index.html'),doc=d.window.document;assert.ok(doc.querySelector('#discover').compareDocumentPosition(doc.querySelector('#events'))&d.window.Node.DOCUMENT_POSITION_FOLLOWING);assert.equal(doc.querySelectorAll('.event-peek').length,6);assert.ok(doc.querySelector('.festival-opening').querySelector('img').src.includes('festival-hero'));d.window.close();});
await test('Cultural tabs restore an explicit place and support Arrow, Home and End keys',()=>{
 const d=make('culture-atlas.html','?place=matsuyama'),w=d.window,doc=w.document;
 assert.equal(doc.querySelector('[role=tab][aria-selected=true]').dataset.fieldChoice,'matsuyama');
 const button=doc.querySelector('[data-field-choice=matsuyama]');button.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(doc.activeElement.dataset.fieldChoice,'uchiko');
 doc.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key:'End',bubbles:true}));assert.equal(doc.activeElement.dataset.fieldChoice,'uwajima');
 doc.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Home',bubbles:true}));assert.equal(doc.activeElement.dataset.fieldChoice,'niihama');
 assert.equal([...doc.querySelectorAll('[role=tabpanel]')].filter(n=>!n.hidden).length,1);assert.equal(doc.querySelectorAll('[role=tab][tabindex="0"]').length,1);d.window.close();
});
await test('Invalid place falls back and no-JS cultural records remain available',()=>{const raw=new JSDOM(read('culture-atlas.html'));assert.equal(raw.window.document.querySelectorAll('[data-field-panel]:not([hidden])').length,4);assert.equal(raw.window.document.querySelectorAll('[data-field-choice][href]').length,4);raw.window.close();const d=make('culture-atlas.html','?place=unknown');assert.equal(d.window.document.querySelector('[role=tab][aria-selected=true]').dataset.fieldChoice,'niihama');d.window.close();});
await test('Each record photograph has original attribution, date and a reusable license',()=>{const rows=JSON.parse(read('assets/culture-sources.json')).images;assert.equal(rows.length,4);for(const r of rows){assert.ok(r.author&&r.date&&r.source&&r.licenseUrl);assert.ok(r.width&&r.height);assert.equal(r.deliveries.length,3);assert.match(r.license,/CC BY-SA/);}assert.match(read('culture-atlas.html'),/1978年製作/);assert.match(read('culture-atlas.html'),/長期休館中/);assert.match(read('culture-atlas.html'),/現地取材・インタビューの記録ではありません/);});
await test('Observation survives a new page without turning entered markup into HTML',()=>{
 const d=make('culture-atlas.html','?place=uchiko'),w=d.window;const input=w.document.querySelector('[data-field-note]');input.value='木の柱 </script><script>alert(1)</script>';w.document.querySelector('[data-field-note-form]').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 const notes=JSON.parse(w.localStorage.getItem('ehime-v2-field-observations'));assert.ok(notes.uchiko);const next=make('notebook.html','',{notes});assert.equal(next.window.document.querySelectorAll('[data-field-journal-list] script').length,0);assert.match(next.window.document.querySelector('[data-field-journal-list]').textContent,/木の柱/);next.window.close();d.window.close();
});
await test('Empty observation does not save; storage failure remains usable and explained',()=>{const d=make('culture-atlas.html','',{blocked:true}),w=d.window,form=w.document.querySelector('[data-field-note-form]');form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.match(w.document.querySelector('[data-field-note-status]').textContent,/入力/);w.document.querySelector('[data-field-note]').value='金糸の輪郭';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.match(w.document.querySelector('[data-field-note-status]').textContent,/保存を利用できません/);d.window.close();});
await test('Deleting observations moves focus and keeps the empty state readable',()=>{const d=make('notebook.html','',{notes:{niihama:'金糸',uchiko:'木の柱',unknown:'不可'}}),w=d.window,doc=w.document;assert.equal(doc.querySelectorAll('[data-remove-field]').length,2);doc.querySelector('[data-remove-field=niihama]').click();assert.equal(doc.activeElement.dataset.removeField,'uchiko');doc.querySelector('[data-remove-field=uchiko]').click();assert.equal(doc.querySelector('[data-field-journal-empty]').hidden,false);assert.equal(doc.activeElement,doc.querySelector('[data-field-journal-empty]'));d.window.close();});
await test('Kana workshop counts small kana, long vowels and sokuon; kanji does not produce a false count',()=>{
 const d=make('culture-literature.html'),w=d.window,doc=w.document;assert.match(doc.querySelector('[data-haiku-status]').textContent,/5・7・5/);
 const input=doc.querySelector('[data-haiku-line="0"]');input.value='ｷｬﾘｰ';input.dispatchEvent(new w.Event('input'));assert.equal(doc.querySelector('[data-haiku-count="0"]').textContent,'3音');input.value='がっこう';input.dispatchEvent(new w.Event('input'));assert.equal(doc.querySelector('[data-haiku-count="0"]').textContent,'4音');input.value='松山';input.dispatchEvent(new w.Event('input'));assert.match(doc.querySelector('[data-haiku-count="0"]').textContent,/読み/);assert.equal(doc.querySelector('[data-haiku-export]').disabled,true);d.window.close();
});
await test('Word export contains the authored poem, remains valid SVG and excludes outside scripts',async()=>{
 const d=make('culture-literature.html'),w=d.window,doc=w.document;let blob,name;w.URL.createObjectURL=b=>{blob=b;return 'blob:poc'};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){name=this.download};doc.querySelector('[data-haiku-export]').click();assert.equal(name,'my-ehime-words.svg');
 const reader=new w.FileReader();const text=await new Promise(resolve=>{reader.onload=()=>resolve(reader.result);reader.readAsText(blob)});const xml=new JSDOM(text,{contentType:'image/svg+xml'});assert.equal(xml.window.document.querySelector('parsererror'),null);assert.match(text,/あきのそら/);assert.doesNotMatch(text,/<script/);xml.window.close();d.window.close();
});
await test('Reading index opens the retained background instead of leaving its target concealed',()=>{const d=make('info-contact-form.html'),doc=d.window.document;const target=doc.querySelector('.reading-disclosure section[id]'),a=doc.querySelector('[href="#'+target.id+'"]');assert.ok(a);assert.equal(target.closest('details').open,false);a.click();assert.equal(target.closest('details').open,true);d.window.close();});
await test('Offline review carries observations and safely embeds script-like personal words',()=>{
 const shell=new JSDOM(read('review.html'),{url:'https://poc.example/review.html',runScripts:'outside-only',virtualConsole:new VirtualConsole()}),w=shell.window;w.scrollTo=()=>{};for(const s of w.document.querySelectorAll('script:not([type])'))w.eval(s.textContent);
 const frame=w.document.getElementById('preview');w.dispatchEvent(new w.MessageEvent('message',{source:frame.contentWindow,data:{type:'ehime-field-notes',notes:{uchiko:'</script><script>alert(1)</script>木の柱'}}}));w.loadPage('notebook.html');
 const child=new JSDOM(frame.srcdoc,{url:'https://poc.example/frame',runScripts:'outside-only',virtualConsole:new VirtualConsole()});child.window.matchMedia=()=>({matches:false,addEventListener(){}});for(const s of child.window.document.querySelectorAll('script'))child.window.eval(s.textContent);assert.equal(child.window.document.querySelectorAll('script[src]').length,0);assert.match(child.window.document.querySelector('[data-field-journal-list]').textContent,/木の柱/);assert.equal(child.window.document.querySelectorAll('[data-field-journal-list] script').length,0);assert.ok(child.window.document.querySelector('[data-field-journal-list] img').src.startsWith('data:image/'));child.window.close();shell.window.close();
});
const report={version:JSON.parse(read('content.json')).version,method:'jsdom source, keyboard event, local storage, safe export and offline continuity checks; not browser confirmation',passed:results.filter(r=>r.status==='PASS').length,total:results.length,results};fs.writeFileSync(path.join(lab,'qa/culture-checks.json'),JSON.stringify(report,null,2)+'\n');process.stdout.write(JSON.stringify(report,null,2)+'\n');if(report.passed!==report.total)process.exitCode=1;
}
main();
